# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a309070b84e0f61c45ada2d313b9a7762eb7f6f978aea43dc0cbdd5ea7e286f8e38b6c5ec450e1cfa38f45a0a44f6065b0fbe3fac02fe59360a4a4cca0717ff8

test:
  secret_key_base: 1356e82db34f59ff385f20b92d9c3b6266885bfce57a6114090db440e6306c678283515c6d8c6be8e39b7480919d1d09eb6d21f7e4e4e695d4a6aac2a4beaf0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
